2022-02-16 09:40:09,485 ERROR: Exception on /reset_password_request [POST] [in C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\ACER\flask_app\app\routes.py", line 175, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\ACER\flask_app\app\emails.py", line 18, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2022-02-16 09:41:15,797 INFO: Microblog startup [in C:\Users\ACER\flask_app\app\__init__.py:45]
2022-02-16 09:41:22,614 ERROR: Exception on /reset_password_request [POST] [in C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\ACER\flask_app\app\routes.py", line 175, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\ACER\flask_app\app\email.py", line 18, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2022-02-16 09:43:12,033 INFO: Microblog startup [in C:\Users\ACER\flask_app\app\__init__.py:45]
2022-02-16 09:54:16,930 INFO: Microblog startup [in C:\Users\ACER\flask_app\app\__init__.py:45]
2022-02-16 10:05:05,844 INFO: Microblog startup [in C:\Users\ACER\flask_app\app\__init__.py:45]
2022-02-16 10:07:45,365 INFO: Microblog startup [in C:\Users\ACER\flask_app\app\__init__.py:45]
2022-02-16 10:24:55,778 INFO: Microblog startup [in C:\Users\ACER\flask_app\app\__init__.py:45]
2022-02-16 10:26:24,077 INFO: Microblog startup [in C:\Users\ACER\flask_app\app\__init__.py:45]
2022-02-16 10:33:02,316 INFO: Microblog startup [in C:\Users\ACER\flask_app\app\__init__.py:45]
2022-02-16 11:03:34,992 INFO: Microblog startup [in C:\Users\ACER\flask_app\app\__init__.py:45]
2022-02-16 11:41:03,679 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
2022-02-16 11:43:44,590 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
2022-02-16 11:46:04,976 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
2022-02-16 11:46:08,892 ERROR: Exception on /edit_profile [GET] [in C:\Python310\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python310\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\routes.py", line 113, in edit_profile
    return render_template('edit_profile.html', title='Edit Profile',
  File "C:\Python310\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Python310\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\templates\edit_profile.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\templates\base.html", line 4, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\templates\base.html", line 37, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\templates\edit_profile.html", line 5, in block 'app_content'
    <h1>{{ _('Edit Profile') }}</h1>
  File "C:\Python310\lib\site-packages\jinja2\utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: '_' is undefined
2022-02-16 11:46:33,297 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
2022-02-16 11:49:11,996 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
