2022-02-15 17:22:39,678 ERROR: Exception on /reset_password_request [GET] [in C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\ACER\flask_app\app\routes.py", line 177, in reset_password_request
    return render_template('reset_password_request.html',
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ACER\flask_app\app\templates\reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ACER\flask_app\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\ACER\flask_app\app\templates\reset_password_request.html", line 8, in block 'content'
    {{ form.password.label }}<br>
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordRequestForm object' has no attribute 'password'
2022-02-15 17:25:41,707 INFO: Microblog startup [in C:\Users\ACER\flask_app\app\__init__.py:45]
2022-02-15 17:25:45,653 ERROR: Exception on /reset_password_request [GET] [in C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\ACER\flask_app\app\routes.py", line 178, in reset_password_request
    return render_template('reset_password_request.html',
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ACER\flask_app\app\templates\reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ACER\flask_app\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\ACER\flask_app\app\templates\reset_password_request.html", line 8, in block 'content'
    {{ form.password.label }}<br>
  File "C:\Users\ACER\.pyenv\pyenv-win\versions\3.9.1\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordRequestForm object' has no attribute 'password'
2022-02-16 10:11:21,577 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:45]
2022-02-16 10:14:30,905 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:45]
2022-02-16 10:23:49,098 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:45]
2022-02-16 10:27:55,596 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:45]
2022-02-16 10:40:13,506 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:45]
2022-02-16 11:02:56,648 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
2022-02-16 11:07:11,261 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
2022-02-16 11:17:23,214 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
2022-02-16 11:19:04,926 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
2022-02-16 11:19:55,768 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
2022-02-16 11:20:46,218 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
2022-02-16 11:24:30,041 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
2022-02-16 11:24:34,644 ERROR: Exception on /login [GET] [in C:\Python310\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\routes.py", line 64, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Python310\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Python310\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\templates\base.html", line 4, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\templates\base.html", line 37, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\templates\login.html", line 5, in block 'app_content'
    <h1>{{ _('Sign In') }}</h1>
  File "C:\Python310\lib\site-packages\jinja2\utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: '_' is undefined
2022-02-16 11:28:47,123 INFO: Microblog startup [in C:\Users\YagneshShukla\Documents\FutureProof\Lap4-Python\Flask_App\flask_app\app\__init__.py:47]
